import type { Service } from "../types";
export const fixture = (patch: Partial<Service> = {}): Service => ({
  id: "1",
  pid: 42,
  name: "node",
  project: "storefront",
  kind: "process",
  ports: [3000],
  addresses: ["*"],
  exposed: true,
  command: "next-server",
  cwd: "/GitHub/storefront/apps/web",
  elapsedSeconds: 36000,
  stoppable: true,
  reason: null,
  stopCommand: "kill -TERM 42",
  cpuPercent: 0.4,
  memoryBytes: 180 * 1024 * 1024,
  parents: [],
  launchGroup: [],
  composeProject: null,
  composeContainers: [],
  ...patch,
});
